GoogleDocPoc/Models/Client.cs
using System;
using System.Collections.Generic;

namespace GoogleDocPoc.Models
{
    public partial class Client
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

GoogleDocPoc/Controllers/ClientController.cs
using GoogleDocPoc.Models;
using GoogleDocPoc.Models.Repository;
using GoogleDocPoc.ViewModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoogleDocPoc.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientRepository clientRepository;
        private ILog _ILog;

        public ClientController(IClientRepository clientRepository)
        {
            this.clientRepository = clientRepository;
        }

        public ClientController()
        {
            this.clientRepository = new ClientRepository();
            _ILog = Log.GetInstance;
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            _ILog.LogException(filterContext.Exception.ToString());
            filterContext.ExceptionHandled = true;
            this.View("Error").ExecuteResult(this.ControllerContext);
        }

        public ActionResult ClientDetails(int? pageNumber)
        {
            ClientViewModel model = new ClientViewModel();
            model.PageNumber = (pageNumber == null ? 1 : Convert.ToInt32(pageNumber));
            model.PageSize = 4;

            List<ClientViewModel> clientDetails = clientRepository.GetClientDetails();
            if (clientDetails != null)
            {
                model.Clients = clientDetails.OrderBy(x => x.Id)
                         .Skip(model.PageSize * (model.PageNumber - 1))
                         .Take(model.PageSize).ToList();

                model.TotalCount = clientDetails.Count();
                var page = (model.TotalCount / model.PageSize) - (model.TotalCount % model.PageSize == 0 ? 1 : 0);
                model.PagerCount = page + 1;
            }
            if (ConfigurationManager.AppSettings["path"] == "FromApp")
            {
                Session["Model"] = model;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AddClient(Client client)
        {
           int i = clientRepository.AddClient(client);
            if (i == 1)
            {
                if (ConfigurationManager.AppSettings["path"] == "FromApp")
                {
                    string directoryPath = Server.MapPath("~/GoogleDocuments\\") + client.Name;
                    if (!Directory.Exists(directoryPath))
                    {
                        Directory.CreateDirectory(directoryPath);
                    }
                }
            }
            return Json(new { Id = i }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult UpdateClient(ClientViewModel clientModel)
        {
           int i = clientRepository.UpdateClient(clientModel.Id, clientModel.Name);
            if (i == 1)
            {
                if (ConfigurationManager.AppSettings["path"] == "FromApp")
                {
                    string path = Server.MapPath("~/GoogleDocuments");
                    string Fromfol = "\\" + clientModel.HdnName + "\\";
                    string Tofol = "\\" + clientModel.Name + "\\";
                    Directory.Move(path + Fromfol, path + Tofol);
                }
            }
            return Json(new { Id = i }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteClient(Client client)
        {
            int i = clientRepository.DeleteClient(client);
            if (i==1)
            {
                if (ConfigurationManager.AppSettings["path"] == "FromApp")
                {
                    string directoryPath = Server.MapPath("~/GoogleDocuments\\") + client.Name;
                    if (Directory.Exists(directoryPath))
                    {
                        Directory.Delete(directoryPath, true);
                    }
                }
            }
            return Json(new { Id = i }, JsonRequestBehavior.AllowGet);
        }
    }
}

GoogleDocPoc/Views/Client/ClientDetails.cshtml
@model GoogleDocPoc.ViewModel.ClientViewModel
@{
    ViewBag.Title = "ClientDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 style="margin-top:35px;">ClientDetails</h2>
@using (Html.BeginForm(FormMethod.Post))
{
    @Html.Hidden("hdnClientName")

    <button type="button" style="margin-left: 15%;" id="btnOpen" class="btn btn-default" onclick="OpenPopup();">Add Client</button>
    <table id="tblClients" class="table table-bordered" style="width:70%;margin-left:15%;margin-top:10px;">
        <thead>
            <tr>
                <th style="width:100px">Client Id</th>
                <th style="width:200px">Client Name</th>
                <th style="width:150px">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var client in @Model.Clients)
            {
                <tr>
                    <td class="Id">
                        <span>@client.Id</span>
                    </td>
                    <td class="Name">
                        <span>@client.Name</span>
                    </td>
                    <td>
                        <a class="Edit" href="javascript:;">Edit</a>
                        <span>|</span>
                        <a class="Delete" href="javascript:;">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5">
                    <ul class="pagination pull-right">
                        @for (int pagenum = 1; pagenum <= @Model.PagerCount; pagenum++)
                        {
                            <li class="paginate_button"><a href="@Url.Action("ClientDetails", "Client", new { pageNumber = @pagenum })" aria-controls="example" data-dt-idx="2" tabindex="0">@pagenum</a></li>
                        }
                    </ul>
                </td>
            </tr>
        </tfoot>
    </table>

    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Client</h4>
                </div>
                <div class="modal-body">
                    <table>
                        <tr id="trClientId" style="display:none;">
                            <td>
                                Client Id :
                            </td>
                            <td>
                                <input type="text" id="txtClientId" readonly="readonly" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Client Name :
                            </td>
                            <td>
                                <input type="text" id="txtClientName" class="form-control" />
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnAdd" class="btn btn-default" onclick="AddClient();">Add</button>
                    <button type="button" id="btnUpdate" style="display:none;" class="btn btn-default" onclick="UpdateClient();">Update</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

}

@section Scripts{
<script type="text/javascript">

    //Webmethod to add Client
    function AddClient()
    {
        var clientName = $("#txtClientName");
        if (clientName.val() == "")
        {
            alert("Please enter Client Name.");
            return false;
        }
        $.ajax
        ({
            type: "POST",
            url: "/Client/AddClient",
            data: '{Name: "' + clientName.val().toUpperCase() + '"}',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (r)
            {
                if (r.Id == 1)
                {
                    alert("Record Inserted Successfully.");
                    $("#myModal").modal('hide');
                    window.location.href = '/Client/ClientDetails';
                    clientName.val("");
                }
                else if (r.Id == 2)
                {
                    alert("Duplicate Record is there with this ClientName " + clientName.val().toUpperCase() + ". ");
                }
                else
                {
                    alert("Record Not Inserted Successfully.");
                }
            }
        });
    }

    //Webmethod to Update Client
    function UpdateClient()
    {
        var clientId = $("#txtClientId");
        var clientName = $("#txtClientName");
        if (clientName.val() == "") {
            alert("Please enter Client Name.");
            return false;
        }

        if ($("#hdnClientName").val() == $("#txtClientName").val().toUpperCase())
        {
            alert("Record Updated Successfully.");
            $("#myModal").modal('hide');
            clientId.val("");
            clientName.val("");
            return false;
        }
        else
        {
            $.ajax
            ({
                type: "POST",
                url: "/Client/UpdateClient",
                data: '{Id: "' + clientId.val() + '",Name: "' + clientName.val().toUpperCase() + '",HdnName: "' + $("#hdnClientName").val().toUpperCase() + '"}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (r)
                {
                    if (r.Id == 1)
                    {
                        alert("Recoed Updated Successfully.");
                        $("#myModal").modal('hide');
                        clientId.val("");
                        clientName.val("");
                        window.location.href = '/Client/ClientDetails';
                    }
                    else if (r.Id == 2)
                    {
                        alert("Duplicate Record is there with this ClientName " + clientName.val().toUpperCase() + ". ");
                    }
                    else
                    {
                        alert("Record Not Updated Successfully.");
                    }
                }
            });
        }
    }

    
    //method to open popup to Add client details
    function OpenPopup() {
        var titleChange = $(".modal-title");
        titleChange[0].innerText = "Add Client";
        $("#txtClientName").val("");
        $("#btnAdd").css("display", "");
        $("#btnUpdate").css("display", "None");
        $("#myModal").modal('show');
    }

    //method to open popup to edit client details
    $("body").on("click", "#tblClients .Edit", function ()
    {
        var titleChange = $(".modal-title");
        titleChange[0].innerText = "Update Client";
        $("#btnAdd").css("display", "None");
        $("#btnUpdate").css("display", "");
        var row = $(this).closest("tr");
        var clientId = row[0].cells[0].innerText;
        var clientName = row[0].cells[1].innerText;
        $("#hdnClientName").val(clientName);
        $("#txtClientId").val(clientId);
        $("#txtClientName").val(clientName);
        $("#myModal").modal('show');
    });

    //Delete event handler.
    $("body").on("click", "#tblClients .Delete", function ()
    {
        if (confirm("Do you want to delete this row?"))
        {
            var row = $(this).closest("tr");
            var clientId = row.find("span")[0].innerText;
            var clientName = row.find("span")[1].innerText;
            $.ajax
            ({
                type: "POST",
                url: "/Client/DeleteClient",
                data: '{Id: "' + clientId + '",Name: "' + clientName + '"}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response)
                {
                    if (response.Id == 1)
                    {
                        row.remove();
                        alert("Record Deleted Successfully.");
                    }
                    else
                    {
                        alert("Record Not Deleted Successfully.");
                    }
                    
                }
            });
        }
    });
    $("#hplClient").addClass("selected");
</script>
}