GoogleDocPoc/Controllers/FileDetailsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using GoogleDocPoc.Models;
using GoogleDocPoc.Models.Repository;
using System.Configuration;

namespace GoogleDocPoc.Controllers
{
    public class FileDetailsController : Controller
    {
        private readonly IFileDetailsRepository fileDetailsRepository;
        private ILog _ILog;

        public FileDetailsController(IFileDetailsRepository fileDetailsRepository)
        {
            this.fileDetailsRepository = fileDetailsRepository;
        }

        public FileDetailsController()
        {
            this.fileDetailsRepository = new FileDetailsRepository();
            _ILog = Log.GetInstance;
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            _ILog.LogException(filterContext.Exception.ToString());
            filterContext.ExceptionHandled = true;
            this.View("Error").ExecuteResult(this.ControllerContext);
        }
        // GET: FileDetails
        public ActionResult Index()
        {
            string roleName = "SuperUser"; int clientId = 1; int userId = 23;
            if (ConfigurationManager.AppSettings["path"] == "FromApp")
            {
                roleName = Session["RoleName"].ToString();
                clientId = Convert.ToInt32(Session["ClientId"]);
                userId   = Convert.ToInt32(Session["UserId"]);
            }
           
            var filePathDetails = new FilePathDetails();
            filePathDetails.FromDate = DateTime.Now.AddMonths(-6).ToString("MM/dd/yyyy");
            filePathDetails.ToDate = DateTime.Now.ToString("MM/dd/yyyy");
            Client obj = new Client {
                Id = 0,
                Name = "Please Select"
            };

            filePathDetails.FilePathDetail = fileDetailsRepository.GetAllFileDetails(roleName, clientId, userId);

            filePathDetails.Clients = fileDetailsRepository.GetAllClientDetails();
            filePathDetails.Clients.Insert(0, obj);

            return View(filePathDetails);
        }

        [HttpPost]
        public JsonResult FormTreeview(int ClientId, int FolderId, string FileName, string FromDate, string ToDate)
        {
            var filePathDetails = new FilePathDetails();

            filePathDetails.FilePathDetail = fileDetailsRepository.GetFilesByFileName(ClientId, FolderId, FileName, FromDate, ToDate);

            return Json(new { result = filePathDetails.FilePathDetail }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult BindFolderDetails(int ClientId)
        {
            List<Folder> folderDetails = fileDetailsRepository.BindFolderDetails(ClientId);

            return Json(new { result = folderDetails }, JsonRequestBehavior.AllowGet);
        }
    }
}

GoogleDocPoc/Controllers/FolderController.cs
using GoogleDocPoc.Models;
using GoogleDocPoc.Models.Repository;
using GoogleDocPoc.ViewModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoogleDocPoc.Controllers
{
    public class FolderController : Controller
    {
        private readonly IFolderRepository folderRepository;
        private ILog _ILog;

        public FolderController(IFolderRepository folderRepository)
        {
            this.folderRepository = folderRepository;
        }

        public FolderController()
        {
            this.folderRepository = new FolderRepository();
            _ILog = Log.GetInstance;
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            _ILog.LogException(filterContext.Exception.ToString());
            filterContext.ExceptionHandled = true;
            this.View("Error").ExecuteResult(this.ControllerContext);
        }

        public ActionResult FolderDetails(int? pageNumber)
        {
            FolderViewModel model = new FolderViewModel();
            model.PageNumber = (pageNumber == null ? 1 : Convert.ToInt32(pageNumber));
            model.PageSize = 4;

            List<FolderViewModel> folderDetails = folderRepository.GetFolderDetails();
            if (folderDetails != null)
            {
                model.Folders = folderDetails.OrderBy(x => x.Id)
                         .Skip(model.PageSize * (model.PageNumber - 1))
                         .Take(model.PageSize).ToList();

                model.TotalCount = folderDetails.Count();
                var page = (model.TotalCount / model.PageSize) - (model.TotalCount % model.PageSize == 0 ? 1 : 0);
                model.PagerCount = page + 1;
            }
            if (ConfigurationManager.AppSettings["path"] == "FromApp")
            {
                Session["Model"] = model;
            }
            return View(model);
        }

        public JsonResult BindClientDetails()
        {
            var clientDetails = folderRepository.BindClientDetails();
            return Json(new { result = clientDetails }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddFolder(FolderViewModel folderModel)
        {
            int i = folderRepository.AddFolder(folderModel.Id,folderModel.FolderName,folderModel.ClientId);
            if (i == 1)
            {
                if (ConfigurationManager.AppSettings["path"] == "FromApp")
                {
                    string directoryPath = Server.MapPath("~/GoogleDocuments\\") + folderModel.ClientName + "\\" + folderModel.FolderName;
                    if (!Directory.Exists(directoryPath))
                    {
                        Directory.CreateDirectory(directoryPath);
                    }
                }
            }
            return Json(new { Id = i }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult UpdateFolder(FolderViewModel folderModel)
        {
            int i = folderRepository.UpdateFolder(folderModel.Id, folderModel.FolderName, folderModel.ClientId);
            if (i == 1)
            {
                if (ConfigurationManager.AppSettings["path"] == "FromApp")
                {
                    string pathFrom = Server.MapPath("~/GoogleDocuments\\") + folderModel.HdnClientName;
                    string pathTo = Server.MapPath("~/GoogleDocuments\\") + folderModel.ClientName;
                    string Fromfol = "\\" + folderModel.HdnFolderName + "\\";
                    string Tofol = "\\" + folderModel.FolderName + "\\";
                    Directory.Move(pathFrom + Fromfol, pathTo + Tofol);
                }
            }
            return Json(new { Id = i }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteFolder(FolderViewModel folderModel)
        {
            int i = folderRepository.DeleteFolder(folderModel.Id);
            if (i == 1)
            {
                if (ConfigurationManager.AppSettings["path"] == "FromApp")
                {
                    string directoryPath = Server.MapPath("~/GoogleDocuments\\") + folderModel.ClientName + "\\" + folderModel.FolderName;
                    if (Directory.Exists(directoryPath))
                    {
                        Directory.Delete(directoryPath, true);
                    }
                }
            }
            return Json(new { Id = i }, JsonRequestBehavior.AllowGet);
        }
    }
}

GoogleDocPoc/Views/Shared/_AddUserPartial.cshtml
@model GoogleDocPoc.ViewModel.UserDetailsViewModel

@using (Html.BeginForm("AddUser", "Registration", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.Hidden("SelectedFolderIds");
    <div id="divUserError" class="col-sm-offset-0 text-danger">
        @Html.ValidationMessage("Error")
    </div>
    <div class="form-group">
        <label for="UserName" class="control-label col-sm-4">UserName</label>
        <div class="col-sm-8">
            @Html.TextBoxFor(a => a.Username, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.Username)
        </div>
    </div>
    <div class="form-group">
        <label for="Password" class="control-label col-sm-4">Password</label>
        <div class="col-sm-8">
            @Html.PasswordFor(a => a.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.Password)
        </div>
    </div>
    <div class="form-group">
        <label for="ConfirmPassword" class="control-label col-sm-4">Conf Pass</label>
        <div class="col-sm-8">
            @Html.PasswordFor(a => a.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.ConfirmPassword)
        </div>
    </div>
    <div class="form-group">
        <label for="Email" class="control-label col-sm-4">Email</label>
        <div class="col-sm-8">
            @Html.TextBoxFor(a => a.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.Email)
        </div>
    </div>
    <div class="form-group">
        <label for="Role" class="control-label col-sm-4">Role</label>
        <div class="col-sm-8">
            @Html.DropDownList("RoleDetails", (IEnumerable<SelectListItem>)ViewBag.RoleDetails, "Select Role", new {@class = "dropdown1 form-control col-sm-8" })
        </div>
    </div>
    <div class="form-group">
        <label for="Client" class="control-label col-sm-4">Client</label>
        <div class="col-sm-8">
            @Html.DropDownList("ClientDetails", (IEnumerable<SelectListItem>)ViewBag.ClientDetails, "Select Client", new {@class = "dropdown1 form-control col-sm-8" })
        </div>
    </div>

    <div class="form-group">
        <label for="Folders" class="control-label col-sm-4">Folders</label>
        <div class="col-sm-8">
            <p id="pFolderDetails">
                <select id="FolderDetails" class="ui-multiselect ui-widget ui-state-default ui-corner-all dvp_gr_ddl form-control col-sm-8" multiple="multiple" name="Folders">
                </select>
            </p>
        </div>
    </div>
    <button type="submit" id="btnAddUser" class="btn btn-primary">Add</button>
}
<script type="text/javascript">
    $(document).ready(function () {
        BindDdl();
        $('#btnAddUser').on('click', function () {
            var message = "";
            var FolderIds = "";
            if ($("#Username").val() == "") {
                message += "Username " + ",";
            }
            if ($("#Password").val() == "") {
                message += " Pasword" + ",";
            }
            if ($("#ConfirmPassword").val() == "") {
                message += " ConfirmPassword" + ",";
            }
            if ($("#Password").val() != $("#ConfirmPassword").val()) {
                message += " Pasword and Confirm Password not same" + ",";
            }
            if ($("#Email").val() == "") {
                message += " Email" + ",";
            }
            if ($("#RoleDetails option:selected").text().trim() == "Select Role") {
                message += "Role" + ",";
            }
            if ($("#ClientDetails option:selected").text().trim() == "Select Client"){
                message += "Client" + ",";
            }
            if (message != ""){
                message = "Error :" + message.substring(0, message.lastIndexOf(','));
                $('#divUserError').html(message);
                return false;
            }
            else{
                $("#SelectedRoleName").val($("#RoleDetails option:selected").text().trim());
                $("#SelectedClientName").val($("#ClientDetails option:selected").text().trim());
                $('#FolderDetails :selected').each(function (i, sel) {
                    FolderIds += $(sel).val() + ',';
                });
                $("#SelectedFolderIds").val(FolderIds.substring(0,FolderIds.length-1));
                return true;
            }
        });

        $("#Username").blur(function () {
            var UserName = $("#Username").val();
            $('#divUserError').html("");
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CheckUserNameForDuplication")',
                dataType: 'json',
                data: { UserName: '' + UserName + '' },
                success: function (status) {
                    if(status==true){
                        $('#divUserError').html("UserName Already exists");
                        return false;
                    }
                } 
            });
            return false;
            });
            
        $("#Email").blur(function () {
            var Email = $("#Email").val();
            $('#divUserError').html("");
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CheckEmailForDuplication")',
                dataType: 'json',
                data: { Email: '' + Email + '' },
                success: function (status) {
                    if (status == true) {
                        $('#divUserError').html("Email Already exists");
                        return false;
                    }
                }
            });
            return false;
        });

        $("#ClientDetails").change(function () {
            BindDdl();
        })

        function BindDdl() {
            $("#FolderDetails").empty();
            var _id= $("#ClientDetails").val();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetFolderDetails")',
                dataType: 'json',
                data: { id:  ''+ _id +''},
                success: function (folderDetail) {
                    var markup = "<select id='FolderDetails' class='ui-multiselect ui-widget ui-state-default ui-corner-all dvp_gr_ddl' multiple='multiple' name='FolderDetails'>";
                    $.each(folderDetail, function (i, data) {
                        markup += "<option value='" + data.Value + "'>" + data.Text + "</option>";
                    });
                    markup += "</select>";
                    $("#pFolderDetails").html(markup).show();
                    $("#FolderDetails").multiselect().multiselectfilter();
                },
                error: function (ex) {
                    alert('Failed to retrieve Folders' + ex);
                }
            });
            return false;
        }
    });
</script>

GoogleDocPoc/Views/Shared/_EditUserPartial.cshtml
@model GoogleDocPoc.ViewModel.UserDetailsViewModel

@using (Html.BeginForm("UpdateUser", "Registration", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.Hidden("MySelectedFolderIds");

    @Html.HiddenFor(a => a.UserId);
    <div id="divUserError" class="col-sm-offset-0 text-danger">
        @Html.ValidationMessage("Error")
    </div>
    <div class="form-group">
        <label for="UserName" class="control-label col-sm-4">UserName</label>
        <div class="col-sm-8">
            @Html.TextBoxFor(a => a.Username, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.Username)
        </div>
    </div>
    <div class="form-group">
        <label for="Password" class="control-label col-sm-4">Password</label>
        <div class="col-sm-8">
           @*@Html.PasswordFor(x => x.Password, new { value = Model.Password})*@
            @Html.PasswordFor(a => a.Password, new { value = Model.Password, @class = "form-control" })
            @Html.ValidationMessageFor(a => a.Password)
        </div>
    </div>
    <div class="form-group">
        <label for="ConfirmPassword" class="control-label col-sm-4">Conf Pass</label>
        <div class="col-sm-8">
            @Html.PasswordFor(a => a.ConfirmPassword, new { value = Model.ConfirmPassword, @class = "form-control" })
            @Html.ValidationMessageFor(a => a.ConfirmPassword)
        </div>
    </div>
    <div class="form-group">
        <label for="Email" class="control-label col-sm-4">Email</label>
        <div class="col-sm-8">
            @Html.TextBoxFor(a => a.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.Email)
        </div>
    </div>
    <div class="form-group">
        <label for="Role" class="control-label col-sm-4">Role</label>
        <div class="col-sm-8">
            @Html.DropDownList("MyRoleDetails", (IEnumerable<SelectListItem>)ViewBag.RoleDetails, "Select Role", new { @class = "dropdown1 form-control col-sm-8" })
        </div>
    </div>
    <div class="form-group">
        <label for="Client" class="control-label col-sm-4">Client</label>
        <div class="col-sm-8">
            @Html.DropDownList("MyClientDetails", (IEnumerable<SelectListItem>)ViewBag.ClientDetails, "Select Client", new { @class = "dropdown1 form-control col-sm-8" })
        </div>
    </div>

    <div class="form-group">
        <label for="Folders" class="control-label col-sm-4">Folders</label>
        <div class="col-sm-8">
            <p id="pMyFolderDetails">
                <select id="MyFolderDetails" class="ui-multiselect ui-widget ui-state-default ui-corner-all dvp_gr_ddl form-control col-sm-8" multiple="multiple" name="MyFolders"></select>
            </p>
        </div>
    </div>
    <button type="submit" id="btnUpdateUser" class="btn btn-primary">Update</button>
}
<script type="text/javascript">
    $(document).ready(function () {

        BindDdl();
        $('#btnUpdateUser').on('click', function () {
            var message = "";
            var FolderIds = "";
            if ($("#Username").val() == "") {
                message += "Username " + ",";
            }
            if ($("#Password").val() == "") {
                message += " Pasword" + ",";
            }
            if ($("#ConfirmPassword").val() == "") {
                message += " ConfirmPassword" + ",";
            }
            if ($("#Password").val() != $("#ConfirmPassword").val()) {
                message += " Pasword and Confirm Password not same" + ",";
            }
            if ($("#Email").val() == "") {
                message += " Email" + ",";
            }
            if ($("#MyRoleDetails option:selected").text().trim() == "Select Role") {
                message += "Role" + ",";
            }
            if ($("#MyClientDetails option:selected").text().trim() == "Select Client")
            {
                message += "Client" + ",";
            }

            if (message != "")
            {
                message = "Error :" + message.substring(0, message.lastIndexOf(','));
                $('#divUserError').html(message);
                return false;
            }
            else
            {
                $('#MyFolderDetails :selected').each(function (i, sel) {
                    FolderIds += $(sel).val() + ',';
                });
                $("#MySelectedFolderIds").val(FolderIds.substring(0, FolderIds.length - 1));
                return true;
            }
        });

        $("#MyClientDetails").change(function () {
            BindDdl();
        })
        function BindDdl() {
            $("#MyFolderDetails").empty();
            var _id= $("#MyClientDetails").val();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetFolderDetails")',
                dataType: 'json',
                data: { id:  ''+ _id +''},
                success: function (folderDetail) {
                    var markup = "<select id='MyFolderDetails' class='ui-multiselect ui-widget ui-state-default ui-corner-all dvp_gr_ddl' multiple='multiple' name='MyFolderDetails'>";
                    $.each(folderDetail, function (i, data) {
                        if (data.Selected == true) {
                            markup += "<option value='" + data.Value + "' Selected >" + data.Text + "</option>";
                        }
                        else{
                            markup += "<option value='" + data.Value + "'>" + data.Text + "</option>";
                        }
                    });
                    markup += "</select>";
                    $("#pMyFolderDetails").html(markup).show();
                    $("#MyFolderDetails").multiselect().multiselectfilter();
                },
                error: function (ex) {
                    alert('Failed to retrieve Folders' + ex);
                }
            });
            return false;
        }
    });
</script>

GoogleDocPoc/Views/Shared/_FileAddPartial.cshtml
@model GoogleDocPoc.Models.FileDetails

@using (Html.BeginForm("AddUpdateFile", "File", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{

    @Html.Hidden("SelectedClientName");
    @Html.Hidden("SelectedFolderName");
    <div id="divError12" class="col-sm-offset-0 text-danger">
        @Html.ValidationMessage("Error")
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1" class="control-label col-sm-4">ClientName</label>
        <div class="col-sm-8">
            @*@Html.DropDownList("ClientDetails", "Select Client")*@
            @Html.DropDownList("ClientDetails", (IEnumerable<SelectListItem>)ViewBag.ClientDetails, "Select Client", new { @class = "form-control col-sm-8" })
        </div>
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1" class="control-label col-sm-4">FolderName</label>
        <div class="col-sm-8">
            @Html.DropDownList("FolderDetails", new SelectList(string.Empty, "Value", "Text"), "Select Folder", new { @class = "form-control col-sm-8" })
        </div>
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1" class="control-label col-sm-4">File</label>
        <div class="col-sm-8">
            <input type="file" id="file" name="file"></input>
        </div>
    </div>
    <button type="submit" id="btnSubmit" class="btn btn-default">Submit</button>
}


<script type="text/javascript">
    $(document).ready(function () {

        $('#btnSubmit').on('click', function () {
            var message = "";
            //var fileSize = $('#file')[0].files[0].size / 1048576;
            if ($("#ClientDetails option:selected").text().trim() == "Select Client")
            {
                message += "ClientName" + ",";
            }
            if ($("#FolderDetails option:selected").val() < "0"){
                message += "FolderName" + ",";
            }
            if ($("#file").val() == "") {
                message += "FileName" + ",";
            }
            else if (($('#file')[0].files[0].size / 1048576) > 5) {
                message += "File size should not be greater then 5MB." + ",";
            }
            else
            {
                var filename = $("#file").val().substring(12, $("#file").val().length);
                var extension = filename.substr((filename.lastIndexOf('.') + 1)).toLowerCase();
                var valid_extensions = /(\.ppt|\.pptx|\.txt|\.pdf|\.docx|\.doc)$/i;
                if (!valid_extensions.test(filename)) {
                    message += "Invalid file type.Please select file with following extention - ppt, pptx, txt, pdf, docx, doc" + ",";
                }
            }
            if (message != "")
            {
                message = "Error :" + message.substring(0, message.lastIndexOf(','));
                $('#divError12').html(message);
                return false;
            }
            else
            {
                $("#SelectedClientName").val($("#ClientDetails option:selected").text().trim());
                $("#SelectedFolderName").val($("#FolderDetails option:selected").text().trim());
                return true;
            }
        });

        $("#ClientDetails").change(function () {
            $("#FolderDetails").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetFolderDetails")',
                dataType: 'json',
                data: { id: $("#ClientDetails").val() },
                success: function (folderDetail) {
                    $.each(folderDetail, function (i, data) {
                        $("#FolderDetails").append('<option value="'
                        + data.Value + '">'
                        + data.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve Folders' + ex);
                }
            });
            return false;
        })
    });
</script>

GoogleDocPoc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GoogleDocsPoc</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <style>
        .selected {
            background-color: gray !important;
        }

        .dropdownmenu ul, .dropdownmenu li {
            margin: 0;
            padding: 0;
        }

        .dropdownmenu ul {
            background: gray;
            list-style: none;
            width: 100%;
        }

        .dropdownmenu li {
            float: left;
            position: relative;
            width: auto;
        }

        .dropdownmenu ul li a {
            padding: 5px;
            background: #5cb85c;
            color: #FFFFFF;
            display: block;
            font: bold 12px/20px sans-serif;
            text-align: center;
            text-decoration: none;
            -webkit-transition: all .25s ease;
            -moz-transition: all .25s ease;
            -ms-transition: all .25s ease;
            -o-transition: all .25s ease;
            transition: all .25s ease;
        }

            .dropdownmenu ul li a:hover {
                background: #333;
            }

        .selected {
            background-color: gray !important;
        }

        .userinfo {
            font-size: 15px;
            color: darkgrey;
            padding-top: 14px;
            padding-right: 15px;
            margin-top: -8px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Survey Study", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="width:100%;">
                <div id="divLogout">
                    <ul class="nav navbar-nav navbar-right">
                        @{
                            var user = Session["UserName"];
                            var role = Session["RoleName"];
                            if (user != null)
                            {
                                <li>@Html.ActionLink("Home", "Index", "FileDetails", new { area = "" }, new { @class = "navbar-brand" })</li>
                                <li class="userinfo">Welcome: @user (@role)</li>
                                <li>@Html.ActionLink("Logout", "LogOut", "Login", new { area = "" }, new { @class = "navbar-brand" })</li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="menuDiv" style="margin-top:-20px;">
        <div id="divMenuList">
            @{
                if (Session["RoleName"].ToString() == "SuperUser")
                {
                    <nav class="dropdownmenu">
                        <ul>
                            <li>@Html.ActionLink("Client", "ClientDetails", "Client", new { area = "" }, new { @id = "hplClient" })</li>
                            <li>@Html.ActionLink("Registration", "UserDetails", "Registration", new { area = "" }, new { @id = "hplRegistration" })</li>
                            <li>@Html.ActionLink("Folders", "FolderDetails", "Folder", new { area = "" }, new { @id = "hplFolder" })</li>
                            <li>@Html.ActionLink("Files", "Index", "File", new { area = "" }, new { @id = "hplFile" })</li>
                        </ul>
                    </nav>
                }
                if (Session["RoleName"].ToString() == "Administrator")
                {
                    <nav class="dropdownmenu">
                        <ul>
                            <li>@Html.ActionLink("Registration", "UserDetails", "Registration", new { area = "" }, new { @id = "hplRegistration" })</li>
                        </ul>
                    </nav>
                }
            }
        </div>
        <div style="text-align: center;font-weight: bold;padding-top:10px;" class="lblDiv">
            <span id="lblFileName"></span>
        </div>
        <div style="" class="">
            @RenderBody()
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <div class="container">
                    <footer>
                        <p style="padding-top:6px;color:gray">&copy; @DateTime.Now.Year - GoogleDocsPoc KANTAR Company</p>
                    </footer>
                </div>
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jquery-ui")
        <link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
        <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js"></script>
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>